### ISSUE TITLE
Enemy mecha standing on dead enemy mecha sometimes display 95% chance-to-hit.

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#28]
title.

**Comment by AmkG** [comment]
This seems to happen when the dead mecha is visually below the living mecha.  If the living mecha is visually rendered below the dead mecha, the correct chance-to-hit is displayed.

**Comment by jwvhewitt** [comment]
I cannot figure this one out. The attack and probability calculating code seems to be correct. The display order should be the order of the mecha in the scene contents list, and that shouldn't have anything to do with which mecha are included in the effect.

After the combat interface upgrade, destroyed mecha will be removed from the scene and this will be a non-issue. Until then I will keep this open because it's a real puzzle.
