### ISSUE TITLE
If you save and exit after a lancemate challenges you but before actually going on the challenge, on reload you will be considered as failing

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#98]
That seems a bit too meta for me.

**Comment by jwvhewitt** [comment]
I think this has been fixed but haven't encountered the plot to test it yet. If anyone can confirm that it doesn't happen now, I will close this.

**Comment by jwvhewitt** [comment]
This plot just came up and the bug is, indeed, fixed.

**Comment by AmkG** [comment]
Now I got the opposite problem --- I lost to the [lancemate](https://github.com/jwvhewitt/gearhead-caramel/issues/129) because he's just much too OP, but the lancemate does not acknowledge my loss and the mission remains in the gate.

**Comment by jwvhewitt** [comment]
I just figured out why- the plot checks to see if the mission has been completed, but the practice duel objective doesn't set the Failed flag. For most missions this is not a problem as incomplete is the same as failed, but because there's an external plot waiting for this mission to be completed, it doesn't work.
I just fixed it by adding a finished property to the mission seed. The finished property gets set to True when a one-shot mission is ended, and the is_completed method checks the finished property before checking the objective status. Unfortunately, this fix will probably break save files.
